x-server: &server
  build:
    context: .
    dockerfile: build/server.Dockerfile

x-client: &client
  build:
    context: .
    dockerfile: build/client.Dockerfile
  cap_add:
    - NET_ADMIN
  extra_hosts:
    - "server:172.21.0.2"
  depends_on: [server, proxy]

services:
  server:
    <<: *server
    networks:
      net_server:
        ipv4_address: 172.21.0.2
        aliases: [backend]

  server-b:
    <<: *server
    networks:
      net_server:
        ipv4_address: 172.21.0.7
        aliases: [backend]

  server-c:
    <<: *server
    networks:
      net_server:
        ipv4_address: 172.21.0.8
        aliases: [backend]

  server-d:
    <<: *server
    networks:
      net_server:
        ipv4_address: 172.21.0.9
        aliases: [backend]

  redis:
    image: redis:7-alpine
    networks:
      net_client:
        ipv4_address: 172.30.0.5

  proxy:
    build:
      context: .
      dockerfile: build/proxy.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "0"
      net.ipv4.ip_local_port_range: "61000 65535"
    ports:
      - "8081:8081"
    networks:
      net_client:
        ipv4_address: 172.30.0.3
      net_server:
        ipv4_address: 172.21.0.3
    depends_on: [server, server-b, server-c, server-d, redis]

  client:
    <<: *client
    networks:
      net_client:
        ipv4_address: 172.30.0.4

  client2:
    <<: *client
    networks:
      net_client:
        ipv4_address: 172.30.0.6

  client3:
    <<: *client
    networks:
      net_client:
        ipv4_address: 172.30.0.10

  client4:
    <<: *client
    networks:
      net_client:
        ipv4_address: 172.30.0.11

networks:
  net_client:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  net_server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
